### ISSUE TITLE
LoadError when require rspec

### ISSUE THREAD

**Issue by lucasVoboril** [Wolox/fictium#13]
## Problem
```
Failure/Error: require 'fictium/rspec'

LoadError:
  cannot load such file -- rspec
``` 

## Solution
Change [this line](https://github.com/Wolox/fictium/blob/4611614ce3464c8ebf5b12e8adfc648cf981f86e/lib/fictium/rspec.rb#L2) to `require_relative 'rspec'`

**Comment by holywyvern** [comment]
Not really a bug, as fictium is not tied to RSpec. RSpec should be required separately as told by documentation.

**Comment by nicozar95** [comment]
I am having the same problem as @lucasVoboril, I am unable to use the gem because it canot load `rspec`
