### ISSUE TITLE
Mediatype deprecation warning

### ISSUE THREAD

**Issue by lucasVoboril** [Wolox/fictium#14]
* Ruby version: 2.6.5
* Rails: 6.0.1

```
DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from process_http_response at ~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/fictium/lib/fictium/rspec/autocomplete/example.rb:11
```

## Solution
Change [this line](https://github.com/Wolox/fictium/blob/4611614ce3464c8ebf5b12e8adfc648cf981f86e/lib/fictium/rspec/autocomplete/example.rb#L11) to `content_type: response.media_type `

**Comment by holywyvern** [comment]
Ressolved as part of GH-11
