### ISSUE TITLE
Supress Body Type when not present

### ISSUE THREAD

**Issue by holywyvern** [Wolox/fictium#24]
**Describe the bug**

The body is added when empty on the operation object, we may ignore it instead.

**To Reproduce**
- Any endpoint with a default example has this.

**Expected behavior**

When there isn't any body, it shouldn't add the requestBody object.

**Rails version:** *any*
**Ruby version:** *any*
**Fictium version:** 0.4.1

**Additional context**

It is required to modify the following line [here](https://github.com/Wolox/fictium/blob/4bc3c97cc474c273fb0ddaba9dfb3beec64c63f4/lib/fictium/exporters/open_api/v3_exporter/example_formatter.rb#L11)

**Comment by tagonzalez** [comment]
Opened PR #25 for this issue

**Comment by blacksam07** [comment]
Close this issue, the related PR is merged
